/* eslint-disable max-statements */
import { ABSOLUTE_ZERO_ºC } from './constants'
import { conversionMap } from './conversionMap'

describe('conversionMap.TEMPERATURE', () => {
  it('should convert temperature units', () => {
    expect(conversionMap.TEMPERATURE.K.K(0)).toEqual(0)
    expect(conversionMap.TEMPERATURE.K.ºC(0)).toBeCloseTo(ABSOLUTE_ZERO_ºC, 1)
    expect(conversionMap.TEMPERATURE.K.ºF(0)).toEqual(-459.7)
    expect(conversionMap.TEMPERATURE.K.ºR(0)).toEqual(0)
    expect(conversionMap.TEMPERATURE.K.ºRe(0)).toEqual(-218.5)
    expect(conversionMap.TEMPERATURE.K.ºD(0)).toEqual(-509.7)
    expect(conversionMap.TEMPERATURE.K.ºN(0)).toEqual(-90.1)

    expect(conversionMap.TEMPERATURE.ºC.K(ABSOLUTE_ZERO_ºC)).toEqual(0)
    expect(conversionMap.TEMPERATURE.ºF.K(-459.67)).toBeCloseTo(0, 1)

    expect(conversionMap.TEMPERATURE.ºC.ºF(0)).toEqual(32)
    expect(conversionMap.TEMPERATURE.ºC.ºF(100)).toEqual(212)
    expect(conversionMap.TEMPERATURE.ºF.ºC(32)).toEqual(0)
    expect(conversionMap.TEMPERATURE.ºF.ºC(100)).toEqual(37.8)
  })
})
describe('conversionMap.DISTANCE', () => {
  it('should convert distance units', () => {
    expect(conversionMap.DISTANCE.m.m(1000)).toEqual(1000)
    expect(conversionMap.DISTANCE.m.km(1000)).toEqual(1)
    expect(conversionMap.DISTANCE.m.dm(1000)).toEqual(10000)
    expect(conversionMap.DISTANCE.m.cm(1000)).toEqual(100000)
    expect(conversionMap.DISTANCE.m.mm(1000)).toEqual(1000000)
    expect(conversionMap.DISTANCE.m.µm(1000)).toEqual(1000000000)
    expect(conversionMap.DISTANCE.m.nm(1000)).toEqual(1000000000000)
    expect(conversionMap.DISTANCE.m.in(1000)).toEqual(39370.079)
    expect(conversionMap.DISTANCE.m.ft(1000)).toEqual(3280.84)
    expect(conversionMap.DISTANCE.m.yd(1000)).toEqual(1093.613)
    expect(conversionMap.DISTANCE.m.mi(1000)).toEqual(0.621)
    expect(conversionMap.DISTANCE.m.nmi(1000)).toEqual(0.54)

    expect(conversionMap.DISTANCE.km.m(1000)).toEqual(1000000)
    expect(conversionMap.DISTANCE.dm.m(1000)).toEqual(100)
    expect(conversionMap.DISTANCE.cm.m(1000)).toEqual(10)
    expect(conversionMap.DISTANCE.mm.m(1000)).toEqual(1)
    expect(conversionMap.DISTANCE.µm.m(1000)).toEqual(0.001)
    expect(conversionMap.DISTANCE.nm.m(1000)).toEqual(0.000001)
    expect(conversionMap.DISTANCE.in.m(1)).toEqual(0.0254)
    expect(conversionMap.DISTANCE.ft.m(1)).toEqual(0.3048)
    expect(conversionMap.DISTANCE.yd.m(1)).toEqual(0.9144)
    expect(conversionMap.DISTANCE.mi.m(1)).toEqual(1609.344)
    expect(conversionMap.DISTANCE.nmi.m(1)).toEqual(1852)

    expect(conversionMap.DISTANCE.km.km(1000)).toEqual(1000)
    expect(conversionMap.DISTANCE.dm.km(1000)).toEqual(0.1)
    expect(conversionMap.DISTANCE.cm.m(1000)).toEqual(10)
    expect(conversionMap.DISTANCE.mm.cm(10)).toEqual(1)
    expect(conversionMap.DISTANCE.µm.cm(1000)).toEqual(0.1)
    expect(conversionMap.DISTANCE.nm.mm(1000)).toEqual(0.001)
    expect(conversionMap.DISTANCE.in.cm(1)).toEqual(2.54)
    expect(conversionMap.DISTANCE.ft.cm(1)).toEqual(30.48)
  })
})
describe('conversionMap.WEIGHT', () => {
  it('should convert weight units', () => {
    expect(conversionMap.WEIGHT.g.g(1000)).toEqual(1000)
    expect(conversionMap.WEIGHT.g.kg(1000)).toEqual(1)
    expect(conversionMap.WEIGHT.g.t(1000)).toEqual(0.001)
    expect(conversionMap.WEIGHT.g.mg(1)).toEqual(1000)
    expect(conversionMap.WEIGHT.g.µg(1)).toEqual(1000000)
    expect(conversionMap.WEIGHT.g.oz(1)).toEqual(0.035)
    expect(conversionMap.WEIGHT.g.lb(1)).toEqual(0.002)
    expect(conversionMap.WEIGHT.g.st(1000)).toEqual(0.157)

    expect(conversionMap.WEIGHT.kg.g(1)).toEqual(1000)
    expect(conversionMap.WEIGHT.t.g(1)).toEqual(1000000)
    expect(conversionMap.WEIGHT.mg.g(1000)).toEqual(1)
    expect(conversionMap.WEIGHT.µg.g(1000)).toEqual(0.001)
    expect(conversionMap.WEIGHT.oz.g(1)).toEqual(28.349523125)
    expect(conversionMap.WEIGHT.lb.g(1)).toEqual(453.59237)
    expect(conversionMap.WEIGHT.st.g(1)).toEqual(6350.29318)

    expect(conversionMap.WEIGHT.kg.t(1000)).toEqual(1)
    expect(conversionMap.WEIGHT.t.kg(1)).toEqual(1000)
    expect(conversionMap.WEIGHT.mg.µg(1)).toEqual(1000)
    expect(conversionMap.WEIGHT.µg.g(1000000)).toEqual(1)
    expect(conversionMap.WEIGHT.oz.lb(16)).toEqual(1)
  })
})
describe('conversionMap.VOLUME', () => {
  it('should convert volume units', () => {
    expect(conversionMap.VOLUME['m³']['m³'](1000)).toEqual(1000)
    expect(conversionMap.VOLUME['m³']['dm³'](1)).toEqual(1000)
    expect(conversionMap.VOLUME['m³']['cm³'](1)).toEqual(1e6)
    expect(conversionMap.VOLUME['m³']['mm³'](1)).toEqual(1e9)
    expect(conversionMap.VOLUME['m³']['µm³'](1)).toEqual(1e18)
    expect(conversionMap.VOLUME['m³']['nm³'](1)).toEqual(1e27)
    expect(conversionMap.VOLUME['m³']['km³'](1e9)).toEqual(1)
    expect(conversionMap.VOLUME['m³'].L(1)).toEqual(1000)

    expect(conversionMap.VOLUME['m³']['m³'](1000)).toEqual(1000)
    expect(conversionMap.VOLUME['dm³']['m³'](1000)).toEqual(1)
    expect(conversionMap.VOLUME['cm³']['m³'](1e6)).toEqual(1)
    expect(conversionMap.VOLUME['mm³']['m³'](1e9)).toEqual(1)
    expect(conversionMap.VOLUME['µm³']['m³'](1e18)).toEqual(1)
    expect(conversionMap.VOLUME['nm³']['m³'](1e27)).toEqual(1)
    expect(conversionMap.VOLUME['km³']['m³'](1)).toEqual(1e9)
    expect(conversionMap.VOLUME.L['m³'](1000)).toEqual(1)

    expect(conversionMap.VOLUME.L['dm³'](1)).toEqual(1)
    expect(conversionMap.VOLUME['cm³']['mm³'](1)).toEqual(1000)
  })
})
